[[section-introduction-and-goals]]
== Introduction and Goals

From many perspectives we consider partner dance as something really great.

* You get together with other people.
* You improve your fine motor skills
* It is in general a pretty healthy thing
* The coordination with the music has also positiv impact on your mental health.
* Great way to find the partner for you life
* With more people dancing, have mor peace on earth ;-)

But there is something that is kind of barrier for many people to practice dancing!

How can they find a partner?

In this project we want to develop a community that brings together people that wants to practice dancing.


=== Requirements Overview

Dancier is aimed to be the goto System for all people looking up dancing related stuff.

This is really kind of a strech goal. So we partitioned the features in two groups.

One that we will really focus on, where we want to make the point. We call them core features.

And the other one additional features.

==== Core features

* Enable the User to tell us want kind of dances he can/likes
* Compute some recommendations for each dancer, want dance partner would match most for him.

Those features are MVP relevant. So they must be included in the MVP:

The following one will be still core, but tackeld after the MVP:

* Enable Dancers and Event-Creators to provide information about upcoming dancing events, like dance evenings. This events will be presented in the same view, like the recommendations for dancers. +
  Those Events could be eg:
** Dance Evening
** Workshops
** Festivals
** Contests
** Dancing Holidays

* Enable Dance-Schools to provided information about themselves. Information for this schools will be included in the recommendation view.

==== Additional features

When we managed that the core features have been implemented, then we can implement the following:

* Allow any other dance related content to popup in the recommendation view where appropriate.
* Improve the Events part: +
** Let the user give information if he joins an event or not.
** In case he joins: +
*** Add him in a temporary chat group only for this event to bring him into contact with others.
** Enable the users to add groups to chat with others.

=== Quality Goals

[options="header", cols="1,2,2"]
|===
|Nr|Quality|Explanation
|1|Easy to use| Dancer should find easy to use features that are almost self-explanatory.
|2|Good recommendations|The recommendations should really fit. In case schools, workshops, shoes and other things where recommended, that should never feel like advertisement but as a good tip.
|3|Attractive|Not only the UI should feel someway modern, also the complete project should feel like what we are: a nice group of people with the strong goal to do something useful for the world ;-)

|===

=== Stakeholders



[options="header",cols="1,1"]
|===
|Role/Name|Contact
| Dancer | Should be able to get in touch with other dancers, to dance with them and share information
| Schools | Should have a fine channel to get in touch with dancer that need courses, workshops and so on
| Shops | Shops for dancing shoes for example connect with dancers
| Developer | Learn in a hollistic way how to develop a complete product. In big companies many developers are so heavily specialized, that the lack a holistic view on software development. And sometimes the do not have a fantastic sympathetic team.
|===
