[[section-architecture-constraints]]

== Architecture Constraints

We are so constrained. Even in multiple dimensions:

=== Technical Constraints
[options="header", cols="1,1,1"]
|===
||Constraint|Background/Motivation
3+|Software and programming constraints
|TC1 |Default Programming Language for Backend development ist Java | This seems to be still a kind a standard language for business backend applications and in the current team, the best understood language
|TC2 |Default for Data related services is Python | This is the defacto standard for such services
|TC3|Default frameworkd for backend development is Spring-Boot| defacto standard in the Java-World
|TC4|Default Database is PostgreSQL| kj
|TC5|Default Object Store is S3 with Minio|
3+|Infrastructure Constraints
|TC6|Everything in a Container|
|TC7|Everything through central IAM|
|TC8|Loggin to Elastic|
|TC9|Traefik|
|===

=== Organizational Constraints

[options="header", cols="1,1,1"]
|===
||Constraint|Background/Motivation
|OC1|Founder is Marc|Dancer, that wants a plattform to connect other dancers together. Wants to learn how to drive a product holistically. May earn something, somewhen with it.

|OC2|Team|Wants to learn how to drive a product holistically. Have a great time working together. Have a reference project. No intention to earn anything with it.
|OC3|Workmode: always pair| Where ever possible, use 4eyes-principle/pair with some other, to achieve mostly to things: share knowledge and grow by this, do not be the one that is not allowed to die

|OC3|Workmode: startup| Only do things that immediatly pay of in the next 6 months. Thins that slow us only down and pay off later: do not do this.
|OC4|Licence|All the source code will be released under an open source license. Everyone can fork the project and start a dancier on his own (with another name of course)
|===

=== Conventions
[options="header", cols="1,1,1"]
|===
||Convention|Reasoning
|C1|Be polite|being aggressive, rude.. will never to anythign good when working together
|C2|Hear first|Confronted with some point of views that seem strange to you have the respect of your collegue that your first thought ist: he will have his reasons. So give him first a chance to explain and then thing about it.
|C3|Code Style|Use the Java Code Style of google. Use PEP8 for python. Aim to follow the principles of clean code.
|===


---
== General
link:https://www.python.org/[Python] as general purpose scripting language::
Writing all scripts that helps the developer. Eg, database
importer/exporter, tools for building, deploying.

== Backend
=== Language
link:https://www.java.com/de/download/[Java 12]::

Java is well known, not only considering the current core team. It has certainly one of
best tooling support. We assume it to be the most popular language for programming modern
backend systems. +
We decided to wanted to have link:https://openjdk.java.net/projects/jigsaw/[Jigsaw] in place,
to start with a pretty modular system even, when staring with monolith. As we want to use
the most recent version of Java, that has mature tooling support and works with other
libraries/frameworks we want to use, we decided to use version 12 of Java.

=== Frameworks
==== Basic
https://spring.io/projects/spring-boot[Spring Boot]::
Decided for it's popularity and it's fast pathed way of setting up typical backend systems.
It relies on the strong foundation of link:https://spring.io/[Spring] for link:https://en.wikipedia.org/wiki/Dependency_injection[Dependency Injection] and link:https://en.wikipedia.org/wiki/Aspect-oriented_programming[AOP], making it easy
to implement enterprise grade systems.

link:https://spring.io/projects/spring-security[Spring Security]::
To secure all endpoints

link:https://spring.io/projects/spring-data-rest[Spring Data Rest]::
To make the creation of link:https://en.wikipedia.org/wiki/Hypertext_Application_Language[HAL] compliant link:https://en.wikipedia.org/wiki/Representational_state_transfer[REST] endpoints a breeze.

==== Persistence
link:https://en.wikipedia.org/wiki/Java_Persistence_API[JPA]::
To map database entities into Java classes. The defacto standard in the Java world.

link:https://www.postgresql.org/[PostgreSQL]::
We assume this is the most advanced relational database, that also supports things like Json datatypes
and has proven for years, it's matureness.

== Frontend
=== Language
link:https://en.wikipedia.org/wiki/JavaScript[JavaScript]/link:https://en.wikipedia.org/wiki/HTML[HTML]/link:https://en.wikipedia.org/wiki/Cascading_Style_Sheets[CSS] as the main language for the frontend.::
We are not sure if we should use Typscript. But HTLM/CSS is out of question.

=== Frameworks
link:https://docs.spring.io/spring/docs/current/spring-framework-reference/web.html#mvc[Spring WebMVC]::
Use for the server side rendering of page with the help of:

link:https://www.thymeleaf.org/[Thymeleaf]::
As the templating engine

link:https://reactjs.org/[React]::
Used to deal with user interaction rich parts of the site. For the current MVP, this
will be the part were the user enters his profile.

== How we to manage Source Code
We are using link:https::/gitbub.com[Github] for:

* all code repositories
* tickets/issues
* code reviews
* building our components

(link:https://github.com/dancier[got to organization])

Working in a project like this together, with multiple developers contributing, requires that each developer
can work on different branches until he finishes his task. Than he merges his changes into to main branch (the master)
to make them available to others.

CCVS (centralized version control systems) support this process just not as good as
link:https://en.wikipedia.org/wiki/Distributed_Concurrent_Versions_System[DVCS].
Whoever worked with multiple branches in eg. SVN knows how complicated it is there to
merge branches.

The drawback of DCVS, that they are admittedly harder to understand, does not count too much for us,
as the whole link:/team.html[core team] already knows GIT.
We also consider DCVS/GIT as the defacto standard in Software Development. So this should not stop others from
contributing.

We have chosen GIT as the concrete representative of a DCVS, as we consider it as
the most used system with the best tooling support.

link:https://github.com[GitHub], is just the most used public available service that offer Git.
It is free for usage in open source projects like this one. It offers additional issues/tickets,
some ci/cd functionality via link:https://github.com/features/actions[actions]
and is due to it's popularity well known among developers.

== Package

We are using link:https://maven.apache.org/[Apache Maven] to build our Software and wrap it into
link:https://www.docker.com/[Docker] link:https://cloud.google.com/containers/[Container].
While Maven is kind of standard, it could be that we switch to
link:https://gradle.org/[Gradle] when we need this flexibility.

In the world of link:https://cloud.google.com/containers/[Containers], link:https://www.docker.com/[Docker] is for sure the standard
with nothing currently really competing as of know. We the recent changes in Management in the Company behind Docker,
this could change in future, but as of now, we are safe.

== Build/Deploy

The build will be triggered in GitHub via link:https://github.com/features/actions[GitHub-Actions]. Once
the project has been build as a Docker Image, it will be uploaded to link:https://github.com/features/packages[GitHub Packages].

Then the following will be triggered

 1. Fetch the docker image from GitHub-Packages
 1. Create new Server-Instance in link:https://www.hetzner.de/cloud[Hetzner-Cloud] via link:https://github.com/hetznercloud/cli[CLI-Tool] or link:https://docs.hetzner.cloud/[Cloud API]
 1. Bootstrap the Server-instance by installing docker in it
 1. Load and start the docker image in the instance
 1. Retarget the load balancer (link:https://www.nginx.com/[NGINX?]) to the new instance if applicable.
 1. Destroy the old instance if everything works



= etc
:jbake-type: page
:jbake-status: published
:jbake-date: 2020-02-23
:jbake-tags: documentation, asciidoctor, document-as-code
:jbake-description: Technologie decisions that does not pay into the core aspects of the project.
:jbake-disqus_enabled: true
:jbake-disqus_identifier:
:idprefix: 59ba274c-69e1-11ea-8d33-0f9436981d6a

== Documentation
We are using link:https://asciidoctor.org/[Asciidoctor] to document everything like:

* project plan
* the site you are just reading
* technical documentation

We decided for Asciidoctor over eg. Markdown as we consider
the first one to be much more potent. Eg. we could include UML
diagram directly in the code. There are also extensions for Markdown
available but Asciidoctor seems just more mature in this area to us.

The asciidoctor files are processed via link:https://jbake.org/[JBake] and
uploaded after every push on the link:https://github.com/dancier/documentation[documentation-repository] via https://github.com/gorzala/frubumi/blob/master/.github/workflows/publish-doc.yml[this GitHub-action]
to this website.
