[[section-concepts]]
== Cross-cutting Concepts

== General
link:https://www.python.org/[Python] as general purpose scripting language::
Writing all scripts that helps the developer. Eg, database
importer/exporter, tools for building, deploying.

== Backend
=== Language
link:https://www.java.com/de/download/[Java 12]::

Java is well known, not only considering the current core team. It has certainly one of
best tooling support. We assume it to be the most popular language for programming modern
backend systems. +
We decided to have link:https://openjdk.java.net/projects/jigsaw/[Jigsaw] in place,
to start with a pretty modular system even, when staring with monolith. As we want to use
the most recent version of Java that has mature tooling support and works with other
libraries/frameworks we want to use, we decided to use version 17 of Java at the beginning but updating it if needed.

=== Frameworks
==== Basic
https://spring.io/projects/spring-boot[Spring Boot]::
Decided for its popularity and its fast pathed way of setting up typical backend systems.
It relies on the strong foundation of link:https://spring.io/[Spring] for link:https://en.wikipedia.org/wiki/Dependency_injection[Dependency Injection] and link:https://en.wikipedia.org/wiki/Aspect-oriented_programming[AOP], making it easy
to implement enterprise grade systems.

link:https://spring.io/projects/spring-security[Spring Security]::
To secure all endpoints

link:https://spring.io/projects/spring-data-rest[Spring Data Rest]::
To make the creation of link:https://en.wikipedia.org/wiki/Hypertext_Application_Language[HAL] compliant link:https://en.wikipedia.org/wiki/Representational_state_transfer[REST] endpoints a breeze.

==== Persistence
link:https://en.wikipedia.org/wiki/Java_Persistence_API[JPA]::
To map database entities into Java classes. The defacto standard in the Java world.

link:https://www.postgresql.org/[PostgreSQL]::
We assume this is the most advanced relational database, that also supports things like Json datatypes
and has proven its maturity for years.

== Frontend
=== Language
link:https://en.wikipedia.org/wiki/JavaScript[JavaScript]/link:https://en.wikipedia.org/wiki/HTML[HTML]/link:https://en.wikipedia.org/wiki/Cascading_Style_Sheets[CSS]/link:https://en.wikipedia.org/wiki/TypeScript[TypeScript] as the main language for the frontend.::
Of course with HTLM5/CSS3 as well as TypeScript.

=== Frameworks
link:https://docs.spring.io/spring/docs/current/spring-framework-reference/web.html#mvc[Spring WebMVC]::
Use for the server side rendering of page with the help of:

link:https://www.thymeleaf.org/[Thymeleaf]::
As the templating engine

link:https://angular.io/[Angular]::
Used to deal with user interaction rich parts of the site.


== How we to manage Source Code
We are using link:https::/gitbub.com[Github] for:

* all code repositories
* tickets/issues
* code reviews
* building our components

(link:https://github.com/dancier[got to organization])

Working in a project like this together, with multiple developers contributing, requires that each developer
can work on a different branch until the task is finished. After a feature is finished, a pull request will be created and reviewed before the branch is merged into the main branch and the feature is available for every developer.

CCVS (centralized version control systems) support this process just not as good as
link:https://en.wikipedia.org/wiki/Distributed_Concurrent_Versions_System[DVCS].
Whoever worked with multiple branches in eg. SVN knows how complicated it is there to
merge branches.

The drawback of DCVS, that they are admittedly harder to understand, does not count too much for us,
as the whole link:/team.html[core team] already knows GIT.
We also consider DCVS/GIT as the defacto standard in Software Development. So this should not stop others from
contributing.

We have chosen GIT as the concrete representative of a DCVS, as we consider it as
the most used system with the best tooling support.

link:https://github.com[GitHub], is just the most used public available service that offers Git.
It is free for usage in open source projects like this one. It offers additional issues/tickets,
some ci/cd functionality via link:https://github.com/features/actions[actions]
and is due to it's popularity well known among developers.

== Package

We are using link:https://maven.apache.org/[Apache Maven] to build our backend software and wrap it into
link:https://www.docker.com/[Docker] link:https://cloud.google.com/containers/[Container].
While Maven is kind of standard, it could be that we switch to
link:https://gradle.org/[Gradle] when we need this flexibility.

In the world of link:https://cloud.google.com/containers/[Containers], link:https://www.docker.com/[Docker] is for sure the standard
with nothing currently really competing as of know. Seeing the recent changes in Management in the Company behind Docker,
this could change in future, but as of now, we are safe.

== Build/Deploy

The build will be triggered in GitHub via link:https://github.com/features/actions[GitHub-Actions]. Once
the project has been build as a Docker Image, it will be uploaded to link:https://github.com/features/packages[GitHub Packages].

Then the following will be triggered

1. Fetch the docker image from GitHub-Packages
1. Create new Server-Instance in link:https://www.hetzner.de/cloud[Hetzner-Cloud] via link:https://github.com/hetznercloud/cli[CLI-Tool] or link:https://docs.hetzner.cloud/[Cloud API]
1. Bootstrap the Server-instance by installing docker in it
1. Load and start the docker image in the instance
1. Retarget the load balancer (link:https://www.nginx.com/[NGINX?]) to the new instance if applicable.
1. Destroy the old instance if everything works



= etc

== Documentation
We are using link:https://asciidoctor.org/[Asciidoctor] to document everything like:

* project plan
* the site you are just reading
* technical documentation

We decided for Asciidoctor over eg. Markdown as we consider
the first one to be much more potent. Eg. we could include UML
diagram directly in the code. There are also extensions for Markdown
available but Asciidoctor seems just more mature in this area to us.

The asciidoctor files are processed via link:https://jbake.org/[JBake] and
uploaded after every push on the link:https://github.com/dancier/documentation[documentation-repository] via https://github.com/gorzala/frubumi/blob/master/.github/workflows/publish-doc.yml[this GitHub-action]
to this website.


=== Technical Constraints
[options="header", cols="1,1,1"]
|===
||Constraint|Background/Motivation
3+|Software and programming constraints
|TC1 |Default Programming Language for Backend development is Java | This seems to be still a kind of standard language for business backend applications and in the current team, the best understood language
|TC2 |Default for Data related services is Python | This is the de facto standard for such services
|TC3|Default framework for backend development is Spring-Boot| defacto standard in the Java-World
|TC4|Default Database is PostgreSQL| kj
|TC5|Default Object Store is S3 with Minio|
3+|Infrastructure Constraints
|TC6|Everything in a Container|
|TC7|Everything through central IAM|
|TC8|Loggin to Elastic|
|TC9|Traefik|

|C3|Code Style|Use the Java Code Style of google. Use PEP8 for python. Aim to follow the principles of clean code.

|===


=== Everything as a container

=== Decouple by time when appropiate

=== Scalability first
* Do not make any decsion that would make it hard to scale up, when needed.


* Responsive Web Design



=== _<Concept 1>_

_<explanation>_



=== _<Concept 2>_

_<explanation>_

...

=== _<Concept n>_

_<explanation>_
