[[section-design-decisions]]
== Design Decisions

=== PostgreSQL as our default Database

[discrete]
==== The problem
Without having a default database, will have the discuss which database system to use for each new service.

So you could argue, that having only one allowed database, would be best.

But this would surely be too restrictive, as we assume that we (at least after our MVP has launched) will have so many different use cases, that will not be addressed all with exactly one database system.

So the question is, what database system is likely to address most of our demands best?

For the rest, each engineer can use another option. In this case he has to write an ADR like this one, pointing out why the default database is not suitable.

[discrete]
==== Influencing Factors
@Sebastian
maybe I mix this up with Assumptions. Can you have a look on the assumptions, if parts of them are influencing factors?


==== Which quality goals are affected?

This decision affects our Reliability Quality Goal.

Issues with our persistence implementation could lead to wrong results, poor performance or even data loss.


[discrete]
==== Which risks are affected?

Besides the quality goals that could be missed, choosing the wrong database could also negatively impact the developer experience. Eg. when we choose something that no one knows, we would have big efforts to learn. Some engineers will like this as they also participate in Dancier to learn something. Other engineers have another focus on what they want to learn and feel distracted to get into a new database system.
In both cases, we will finish our goals later, because of the learning effort.


[discrete]
==== Assumptions

In most cases, we will have to deal with structured data. We also know that the current team has its best knowledge using SQL databases.

We also expect that we are quite likely in a situation, where we need database transactions for implementing patterns like the outbox pattern.

We also do not expect that most of our database will not need to scale horizontally. If this assumption turns out to be false, then we expect that moving to another database system will be not too expensive, as we follow the clean architecture style or at least the DAO pattern.

[discrete]
==== Option we take a look on

[discrete]
==== MongoDB
MongoDB's main advantage of offering transparent sharding does not pay off for us, as we (see assumptions) do not need horizontal scaling.

Storing arbitrary JSON-Documents is also not an advantage (compared to PostgreSQL), as 

 1. We in general deal with structured data (see assumptions)
 1. PostgreSQL also can store JSON, in case we would need it


We also still have pretty limited know-how in the core team, as opposed to PostgreSQL.


[discrete]
==== PostgreSQL
SQL databases are still the most widely used database systems (links). 
PostgreSQL seems to be the most used Open Source database system used professionally (link).

Everyone in the Team can use PostgreSQL as everyone is aware of the ideas of relational databases.

Relational Databases are pretty mature and supported by Frameworks like Boot that we use. Tooling is also very mature.

We have also experience in operating PostgreSQL.


[discrete]
==== Cassandra
Almost the same as with MongoDB, while Tooling Support is expected to be the least mature under our three options.

[discrete]
==== Decision

We decided that PostgreSQL is our default database.

This could be deducted from our link:https://project.dancier.net/architecture-decision-principles.html[architectural decision principles]:

===== Skills of team members(AP3)/Principle of least surprise(AP6)
 * bad experience with MongoDB and Cassandra on former work projects
 * best knowledge here will lead to less surprise as problems could be anticipated more, that with the other less known products
 
===== Go Deep not wide (AP5)

Defaulting to the world's most prominent database architecture (SQL) makes us more experts in that very important technology and less half experts in more than one.

We expect a better overall result, by understanding better less technologies, than less understanding of more technologies.

===== Favor what's proven
For sure, SQL is the most proven database system out there (link?) and PostgreSQL is one of the top open-source candidates.

=== Python for all Data science related tasks

[discrete]
==== The problem
One of our top quality goals is the the recommendations we offer to our dancers should be good.
So we want to use best tooling and frameworks that helps us in implementing a good recommender.
Our main langugage ist Java. So at first we could implement the recommender in Java.


=== Computing Recommendations in its own deployable

[discrete]
==== The problem
As we decided to have have Python for all data science realted stuff. 

=== Self Contained System for Kikerki


=== Batch Mode for computing the recommendations








