= Making reasonable technology decisions
:jbake-type: page
:jbake-status: published
:jbake-date: 2023-11-14
:jbake-tags: desgin pattern, architecture, java, kiss, agile, decision making, technology
:jbake-description: Describe how we are making architectural decisions
:jbake-disqus_enabled: true
:jbake-disqus_identifier: d23e2d10-c1a6-11ed-8bd8-3b33f0bea9fd
:idprefix:

Why do we think having aligned architectural principles is a good idea...

== The Problem

Let's think about what could happen when you take two developers, and lock them up in a room until they have a consensus on what is the best programming language they should pick up for the next project.

From my experience that could end up not so nice. Without getting deeper into how they would look like after 10 hours, I would bet they will not find consensus in quite many cases. We guess that the reason is, that they will likely argue more preference-based which will turn out to get personal pretty fast.

https://www.meeteor.com/post/principle-based-decision-making[Read this to know why we think so].

So we want to provide our members with principles that guide them through a smooth decision-making process, with the best result for Dancier.

== The Principles by Categories

=== General
[cols="1,2,6"]
|===
|Id|Name|Description

|AP1
|Low Coupling, High Cohesion
|Strive for low coupling, where modules minimize dependencies on each other,
ensuring changes in one module have minimal impact on others.
Simultaneously, pursue high cohesion within modules,
ensuring closely related code elements work together seamlessly,
fostering maintainability, readability and efficient development.

|AP2
|Keep it simple stupid (KISS)
a|Based on our interpretation of
https://en.wikipedia.org/wiki/Agile_software_development[Agile Development]
we think that we should choose the https://en.wikipedia.org/wiki/KISS_principle[simplest] approach to tackle a task. +

Particularly, we always try to avoid optimizing things before it turns out
that optimization is needed (https://ubiquity.acm.org/article.cfm?id=1513451[see Donald Knuth]).
This applies, in the same way, to _small_ things eg.

* optimizing algorithms like SQL queries
* choosing frameworks for persistence, offering rest endpoints, frontend frameworks
* infrastructural topics like VCS build system

As well as it applies to "bigger" things eg.

     * Deciding architectural things like using CQRS
     * Using microservices vs. putting things into a monolith

|AP3
|Favor what is proven
a|     Default for standard options. Eg. when there are several similar web frameworks, go for the more prominent one. Because we expect that:
 
      * we are getting more support from other developers if we run into problems
      * expect more support from the upstream project itself, and also the project itself will exist for a longer time
      * have better tooling support (if applicable)
      * have it easier to find more developers


|AP4
|Go deep not wide
|Technical diversity will be controlled to reduce complexity.

|AP5
|Principle of Least Surprise
|Build software and design the architecture such that it doesn't surprise users or fellow developers.
When making decisions, prioritize predictability and ease of use over cleverness and novelty.
This general principle can be applied to many aspects,
such as making architectural decisions as well as building a clear UI for the end user.

|AP6
|Delay Design Decisions
|Delay design decisions until they are necessary.
Decisions should be made at the last responsible moment, fostering a culture of experimentation.
This will gather new insights that can be used to iteratively design the architecture.
No point in designing and implementing capabilities upfront may never be used
- it is a waste of time and resources.


|AP7
| Match techniques with skills of core team members
| The chosen technique should be either already known by the team (or part of the team) or the team must be willing to learn it.

|===

