[[section-solution-strategy]]
== Solution Strategy

=== Login/Registration

[plantuml,login-registration-states,svg]
....
@startuml

    [*] -> LandingPage
    LandingPage --> LoginBase: login
    LandingPage --> RegisterBase: register
    RegisterBase --> CheckHumanityRegister

    LoginBase --> CheckCredentials: user/pass-login
    LoginBase --> LoginLink: login_link_requested
    LoginBase --> PasswordReset: pass_reset_requested

    CheckCredentials --> LoginSuccess: valid_credentials
    LoginSuccess --> [*]
    CheckCredentials --> LoginBase: invalid_credentials

    LoginLink --> CheckHumanityLoginLink: login_link_requested
    PasswordReset --> CheckHumanityPasswordReset: password_reset_requested

    CheckHumanityLoginLink --> SendLoginLink
    SendLoginLink --> LoginPerformed: on_click
    LoginPerformed --> [*] : success
    LoginPerformed --> LoginBase: login_failure

    CheckHumanityPasswordReset --> SendPassResetLink
    SendPassResetLink -> PerformLoginOnPasswordReset: on_click

    PerformLoginOnPasswordReset --> ChangePassword: success
    PerformLoginOnPasswordReset --> LoginBase: failure
    ChangePassword --> [*]

    CheckHumanityRegister --> PerformRegistration
    PerformRegistration --> SendEmailVerificationLink: account_does_not_exist
    PerformRegistration --> SendAccountAlreadyExistMail: account_already_exist
    SendAccountAlreadyExistMail --> LoginPerformed: on_login_click
    SendAccountAlreadyExistMail --> SendPassResetLink


    SendEmailVerificationLink --> PerformEmailVerification
    PerformEmailVerification --> LoginPerformed: success
    PerformEmailVerification --> ResendEmailVerification
    ResendEmailVerification --> PerformEmailVerification
@enduml
....
foo
[plantuml,login-activity,svg]
....
@startuml

start
switch (choose a login mode)
case (via login data)
    : enter username/password;
    if() then (login data valid)
        :log in successful;
        stop
    else (login data invalid)
        :login failed;
        stop
    endif
case (via login link)
  #00FF00: request login link;
    floating note right: green: human/bots check required
            : click on login link;
                if() then (link valid)
                    :log in successful;
                    stop
                else (link invalid)
                    :log in failed;
                    stop
                endif
case (reset password)
  #00FF00:Request Password Reset;
  :click on password reset link;
    if() then (link valid)
        :pw reset successful;
        stop
    else (link invalid)
        :pw reset failed;
        stop
    endif
endswitch

@enduml
....

[plantuml,registration-activity,svg]
....
@startuml

start
:fill registration form;
#00FF00:send registration request;
floating note right: green: human/bots check required
if(user exists) then (yes)
    :account already exists mail receive;
    if(click on links in the mail) then (login link)
        :goto login flow;
        stop
    else (password reset link)
        :goto password reset flow;
        stop
    endif
else (no)
    :registration verification link received;
    :click on verification link;
    if() then (link valid)
        :registration successful;
        stop
    else (link invalid)
        :mail verification failed;
        #00FF00:request a new verification mail;
        stop
    endif

endif

@enduml
....
