:jbake-type: post
:jbake-status: published
:jbake-tags: blog, asciidoc
:idprefix:
= Project

As we are all not being paid for what we are doing here (and we are
also not planning that this changes in the (nearer) future, we will
not define project plan that includes dates.

We are defining the content of the next release and will just work
towards it.

As the project was just kicked of, we have not released anything.
The first release will be what is call an

link:https://en.wikipedia.org/wiki/Minimum_viable_product[MVP] and
this is being defined in the next section.

== Our first version

This version should already by useful, in that way that people should
be able to find partners to dance with.

The following functionality should be implemented:

 * User should have the ability to create an account
 * Users with account should have the ability to create a profile with the at least the following information
 ** Nickname (öffentlicher Name)
 ** Zip Code and or City
 ** type of dance (Tango, Salza, Standard, ...)
 ** searching for just an evening and/or a course
 * User with an account should be able to see a list of all other users
 * Users without an account should only see a landing page with
   information about what this page is about.
 * Users should be able to create an account by email adress and password,
   as well as with facebook

TBD: create Mockups to indicate the planned flow through the site.

== Ideas for versions after the MVP
 * Add dancing schools to the project, that can be displayed on
   relevant pages.
