= What we use and why we use it
:jbake-type: page
:jbake-status: published
:jbake-date: 2020-02-23
:jbake-tags: desgin pattern, architecture, java, kiss, agile, decision making
:jbake-description: Describe how we are making (not only technial) decisions
:jbake-disqus_enabled: true
:jbake-disqus_identifier: 6402d4ec-69e1-11ea-8a83-5f9a72c4b212
:idprefix:

In this section, we describe the basic rules we try to follow when making decisions like:

 * what kind of version control system (VCS) we use
 * what database we will use
 * what basic frameworks will be used
 * what should be the programming language(s)
 * ....

To have some guidance in the process of making decisions we have
written down the following rules as a _rough_ guide.

== Key drivers for technical decisions

 1. *Any decision should be as little opinionated as possible* +
    We should never choose a technology just because we consider
    it eg. cool or only because we have experienced it as a good fit for _another_ use case.
    Decisions should be made depending on the use case. +
 1. *Keep it simple stupid (KISS)* +
    Based on our interpretation of
    https://en.wikipedia.org/wiki/Agile_software_development[Agile Development]
    we think that we should choose the https://en.wikipedia.org/wiki/KISS_principle[simplest] approach to tackle a task.
    Particularly, we always try to avoid optimizing things before it turns out
    that optimization is really needed (https://ubiquity.acm.org/article.cfm?id=1513451[see Donald Knuth]).
    This applies in the same way to _small_ things eg.
     * optimizing algorithms like SQL-queries
     * choosing frameworks for persistence, offering rest endpoints, frontend frameworks
     * infrastructural topics like VCS build system +
+
As well as it applies to "bigger" things eg.
     * Deciding architectural things like using CQRS
     * Using microservices vs. putting things into a monolith
 1. *Choosing standard* +
    Try to use standard options. Eg. when there are several similar web frameworks,
    go for the more prominent one. Because for the more prominent one we will
      * get more support from other developers if we run into problems
      * expect more support from the project itself, and also the project itself will exist longer
      * have better tooling support (if applicable)
      * have it easier to find more developers
 1. *Match techniques with skills of core team members* +
    The chosen technique should be either already known by the team (or part of the team) or the team must
    be willing to learn it.

It is obvious that some criteria could be in conflict with others. Then we use just common sense.

== Read more about concrete decisions that have been taken
 * link:main.html[Main]
 * link:infrastructure.html[Infrastructure]
