= Infrastructure
:jbake-type: post
:jbake-status: published
:jbake-tags: blog, asciidoc
:idprefix:

:toc:
:toc-placement: macro
toc::[]

== How we to manage Source Code
We are using link:https::/gitbub.com[Github] for:

* all code repositories
* tickets/issues
* code reviews
* building our components

(link:https://github.com/dancier[got to organization])

Working in a project like this together, with multiple developers contributing, requires that each developer
can work on different branches until he finishes his task. Than he merges his changes into to main branch (the master)
to make them available to others.

CCVS (centralized version control systems) support this process just not as good as
link:https://en.wikipedia.org/wiki/Distributed_Concurrent_Versions_System[DVCS].
Whoever worked with multiple branches in eg. SVN knows how complicated it is there to
merge branches.

The drawback of DCVS, that they are admittedly harder to understand, does not count too much for us,
as the whole link:/team.html[core team] already knows GIT.
We also consider DCVS/GIT as the defacto standard in Software Development. So this should not stop others from
contributing.

We have chosen GIT as the concrete representative of a DCVS, as we consider it as
the most used system with the best tooling support.

link:https://github.com[GitHub], is just the most used public available service that offer Git.
It is free for usage in open source projects like this one. It offers additional issues/tickets,
some ci/cd functionality via link:https://github.com/features/actions[actions]
and is due to it's popularity well known among developers.

== Deploy/Package
We plan to package all our deployable units into link:https://cloud.google.com/containers/[Container].
Concrete we are using link:https://www.docker.com/[Docker] as the container technologie.

== Build
We use link:https://maven.apache.org/[Maven] to build the project and remotely link:https://github.com/features/actions[GitHub-Actions] to execute the build.


