= Infrastructure
:jbake-type: page
:jbake-status: published
:jbake-tags: infrastructur, ccvs, dvcs, git, cloud, deployment
:jbake-date: 2020-02-23
:jbake-description: Describe the infrastructure we use for development and deployment
:jbake-disqus_enabled: true
:jbake-disqus_identifier: 6ef41d66-69e1-11ea-8467-b30d35089e34
:idprefix:

:toc:
:toc-placement: macro
toc::[]

== How we to manage Source Code
We are using link:https::/gitbub.com[Github] for:

* all code repositories
* tickets/issues
* code reviews
* building our components

(link:https://github.com/dancier[got to organization])

Working in a project like this together, with multiple developers contributing, requires that each developer
can work on different branches until he finishes his task. Than he merges his changes into to main branch (the master)
to make them available to others.

CCVS (centralized version control systems) support this process just not as good as
link:https://en.wikipedia.org/wiki/Distributed_Concurrent_Versions_System[DVCS].
Whoever worked with multiple branches in eg. SVN knows how complicated it is there to
merge branches.

The drawback of DCVS, that they are admittedly harder to understand, does not count too much for us,
as the whole link:/team.html[core team] already knows GIT.
We also consider DCVS/GIT as the defacto standard in Software Development. So this should not stop others from
contributing.

We have chosen GIT as the concrete representative of a DCVS, as we consider it as
the most used system with the best tooling support.

link:https://github.com[GitHub], is just the most used public available service that offer Git.
It is free for usage in open source projects like this one. It offers additional issues/tickets,
some ci/cd functionality via link:https://github.com/features/actions[actions]
and is due to it's popularity well known among developers.

== Package

We are using link:https://maven.apache.org/[Apache Maven] to build our Software and wrap it into
link:https://www.docker.com/[Docker] link:https://cloud.google.com/containers/[Container].
While Maven is kind of standard, it could be that we switch to
link:https://gradle.org/[Gradle] when we need this flexibility.

In the world of link:https://cloud.google.com/containers/[Containers], link:https://www.docker.com/[Docker] is for sure the standard
with nothing currently really competing as of know. We the recent changes in Management in the Company behind Docker,
this could change in future, but as of now, we are safe.

== Build/Deploy

The build will be triggered in GitHub via link:https://github.com/features/actions[GitHub-Actions]. Once
the project has been build as a Docker Image, it will be uploaded to link:https://github.com/features/packages[GitHub Packages].

Then the following will be triggered

 1. Fetch the docker image from GitHub-Packages
 1. Create new Server-Instance in link:https://www.hetzner.de/cloud[Hetzner-Cloud] via link:https://github.com/hetznercloud/cli[CLI-Tool] or link:https://docs.hetzner.cloud/[Cloud API]
 1. Bootstrap the Server-instance by installing docker in it
 1. Load and start the docker image in the instance
 1. Retarget the load balancer (link:https://www.nginx.com/[NGINX?]) to the new instance if applicable.
 1. Destroy the old instance if everything works

