= Main
:jbake-type: post
:jbake-status: published
:jbake-tags: blog, asciidoc
:idprefix:

:toc:
:toclevels: 5
:toc-placement: macro
toc::[]

== General
link:https://www.python.org/[Python] as general purpose scripting language::
Writing all scripts that helps the developer. Eg, database
importer/exporter, tools for building, deploying.

== Backend
=== Language
link:https://www.java.com/de/download/[Java 12] as the main Backend programming language::

Java is well known, not only considering the current core team. It has certainly one of
best tooling support. We assume it to be the most popular language for programming modern
backend systems. +
We decided to wanted to have link:https://openjdk.java.net/projects/jigsaw/[Jigsaw] in place,
to start with a pretty modular system even, when staring with monolith. As we want to use
the most recent version of Java, that has mature tooling support and works with other
libraries/frameworks we want to use, we decided to use version 12 of Java.


=== Frameworks
==== Basic
https://spring.io/projects/spring-boot[Spring Boot]::
Decided for it's popularity and it's fast pathed way of setting up typical backend systems.
It relies on the strong foundation of link:https://spring.io/[Spring] for link:https://en.wikipedia.org/wiki/Dependency_injection[Dependency Injection] and link:https://en.wikipedia.org/wiki/Aspect-oriented_programming[AOP], making it easy
to implement enterprise grade systems.

link:https://spring.io/projects/spring-security[Spring Security]::
To secure all endpoints

link:https://spring.io/projects/spring-data-rest[Spring Data Rest]::
To make the creation of link:https://en.wikipedia.org/wiki/Hypertext_Application_Language[HAL] compliant link:https://en.wikipedia.org/wiki/Representational_state_transfer[REST] endpoints a breeze.

==== Persistence
link:https://en.wikipedia.org/wiki/Java_Persistence_API[JPA]::
To map database entities into Java classes. The defacto standard in the Java world.

link:https://www.postgresql.org/[PostgreSQL]::
We assume this is the most advanced relational database, that also supports things like Json datatypes
and has proven for years, it's matureness.

== Frontend
=== Language
link:https://en.wikipedia.org/wiki/JavaScript[JavaScript]/link:https://en.wikipedia.org/wiki/HTML[HTML]/link:https://en.wikipedia.org/wiki/Cascading_Style_Sheets[CSS] as the main language for the frontend.::
We are not sure if we should use Typscript. But HTLM/CSS is out of question.

=== Frameworks
link:https://docs.spring.io/spring/docs/current/spring-framework-reference/web.html#mvc[Spring WebMVC]::
Use for the server side rendering of page with the help of:

link:https://www.thymeleaf.org/[Thymeleaf]::
As the templating engine

link:https://reactjs.org/[React]::
Used to deal with user interaction rich parts of the site. For the current MVP, this
will be the part were the user enters his profile.

