name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Bake the site
      run: ./gradlew bake
    - name: ftp-action
      uses: sebastianpopp/ftp-action@v1.1.0
      with:
        # FTP host
        host: ${{ secrets.DOCU_FTP_HOST }}
        # FTP userg
        user: ${{ secrets.DOCU_FTP_USER }}
        # FTP password
        password:  ${{ secrets.DOCU_FTP_PASS }}
        # Local directory
        localDir: build/docs/html5/site/
