= Documentation
:jbake-type: page
:jbake-status: published
:jbake-date: 2020-02-23
:jbake-tags: architecture, microservice, cloud
:jbake-description: Functional and technial description of the project
:jbake-author: Marc Gorzala
:jbake-disqus_enabled: true
:jbake-disqus_identifier: 8aa2a992-69e1-11ea-9148-6b22f65ee646
:idprefix:

:toc:
:toclevels: 5
:toc-placement: macro
toc::[]

== Infrastructure
Here everything will be described, what we utilize to

 1. develop our project
 1. deploy and run our project

=== Develop
To be written

=== Deploy and Run

We are planing to deploy our project in the link:https://www.hetzner.de/cloud[Hetzner Cloud].

[plantuml, cloud-architecture, svg]
....
@startuml
left to right direction
actor user
actor deployer
component browser
cloud VPC {
   database db
   boundary loadbalancer
   node {
     node dancer1
     node dancer2
     node dancern
   }
}
user -- browser
browser -- loadbalancer
loadbalancer -- dancer1
loadbalancer -- dancer2
loadbalancer -- dancern
dancer1 -- db
dancer2 -- db
dancern -- db

deployer -- dancer1
deployer -- dancer2
deployer -- dancern

@enduml
....

At least for the link:/project/index.html[first iteration] our running
setup in the cloud will cover three different services:

 1. A load balancer like link:https://containo.us/traefik/[Traefik] +
    This will be the only component that will receive direct traffic
    from users from the internet. It will sit on the limes of our
    link:https://en.wikipedia.org/wiki/Virtual_private_cloud[VPC]
    and act as an link:https://en.wikipedia.org/wiki/TLS_termination_proxy[SSL terminating proxy].
    The traffic will be forwarded into the VPC to the dancer component, that
    contain our main application. +
    When the traffic demand it (not in the nearer future, we are not that
    optimistic) the loadbalancer will distribute the incoming request in a
link:https://www.nginx.com/resources/glossary/round-robin-load-balancing/[round robin]
    fashion.
 1. Our one one only main component the *dancer* +
    Sits between the load balancer and the database. Is reachable for
    deployment from the deployer for releasing new versions.
 1. Our Database Server like link:https://www.postgresql.org/[PostgreSQL] +
    Will have a connection


We will wrap all above mentioned components into Docker Containers, to
unify the process of deploying each of them.

== Login
First we will only offer Facebook Login for our users. It is planned to extend that to Google Login and Apple-Id.

[plantuml, Login, svg]
....
@startuml
User -> "Facebook Login": GET
"Facebook Login" -> "Backend Callback": redirect to
"Backend Callback" -> "Facebook Token Endpoint": exchange
"Backend Callback" -> ""
@enduml
....
